
from MM1_DEFS import * # This imports Colors


USE_SESSION_VIEW = True # Set to false if you don't want this feature

N_TRACKS = 1 
N_SCENES = 1 


TRACK_CLIP_BUTTONS = [3] 

FILTER_DIALS = [18, 19, 20, 21]

CLIP_STARTED_COLOR = C_GREENB 
CLIP_STOP_COLOR = C_GREEN 
CLIP_TRG_PLAY_COLOR = C_BLUEB 
NO_CLIP_COLOR = C_AMBER


USE_SESSION_NAV = True 
NAVBOX_LEFT_BUTTON = 16
NAVBOX_LEFT_BUTTON_C = C_BLUE
NAVBOX_RIGHT_BUTTON = 17
NAVBOX_RIGHT_BUTTON_C = C_PINK
NAVBOX_UP_BUTTON = 121
NAVBOX_UP_BUTTON_C = C_BLUE
NAVBOX_DOWN_BUTTON = 122
NAVBOX_DOWN_BUTTON_C = C_PINK

#ZOOM_STOPPED = C_PINK
#ZOOM_PLAYING = C_GREEN
#ZOOM_SELECTED = C_BLUE


USE_MIXER_CONTROLS = True


USE_SENDS = False
#N_SENDS_PER_TRACK = 3 # sends per track
#SEND_ENCODERS = [1,2,3,9,10,11,17,18,19,25,26,27] 

USE_MIXER_EQ = True
USE_MIXER_FILTERS = True

USE_STOP_BUTTONS = False
STOP_BUTTONS = [52, 53, 54, 55] 
STOP_BUTTON_ON_COLOR = C_GREEN
STOP_BUTTON_OFF_COLOR = C_AMBER

USE_SELECT_BUTTONS = False
SELECT_BUTTONS = [20, 21, 22, 23] 
SELECT_BUTTON_ON_COLOR = C_GREEN
SELECT_BUTTON_OFF_COLOR = C_AMBER

USE_DEVICE_NAV_BUTTONS = False
DEVICE_NAV_BUTTONS = [16, 17, 18, 19]

USE_MUTE_BUTTONS = False
MUTE_BUTTONS = [64, 65, 66, 67] 
MUTE_BUTTON_ON_COLOR = C_GREEN
MUTE_BUTTON_OFF_COLOR = C_AMBER

USE_ARM_BUTTONS = False
ARM_BUTTONS = [72, 73, 74, 75] 
ARM_BUTTON_ON_COLOR = C_GREEN
ARM_BUTTON_OFF_COLOR = C_AMBER

USE_SOLO_BUTTONS = True
SOLO_BUTTONS = [48, 49, 50, 51]
SOLO_BUTTON_ON_COLOR = C_GREEN
SOLO_BUTTON_OFF_COLOR = C_AMBER

# VOLUME_ENCODERS can be any length <= N_TRACKS
USE_VOLUME_CONTROLS = True
VOLUME_ENCODERS = [48, 49, 50, 51]
############################

